# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-23 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    def setSlugs(apps, schema_editor):
        ContactList = apps.get_model('viewsenators', 'ContactList')
        for i, model in enumerate(ContactList.objects.all()):
            model.slug = model.uid.hex
            model.save()

    dependencies = [
        ('viewsenators', '0002_contactlist_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactlist',
            name='slug',
            field=models.SlugField(unique=True, null=True, editable=False),
        ),
        migrations.RunPython(setSlugs),
        migrations.AlterField(
            model_name='contactlist',
            name='slug',
            field=models.SlugField(unique=True, null=False, editable=False),
        ),
    ]
