# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-01-08 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewsenators', '0005_add_state_population'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='facebookId',
            field=models.CharField(max_length=17),
        ),
    ]
