# Generated by Django 3.0.2 on 2020-01-31 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewsenators', '0007_add_moc_phonenumbers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='abbrev',
            field=models.CharField(max_length=2),
        ),
    ]
